connectedin/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path
from perfis import views
from usuarios.views import RegistrarUsuarioView
from django.contrib.auth import views as v

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('perfil/<int:perfil_id>', views.exibir_perfil, name='exibir'),
    path('perfis/<int:perfil_id>', views.convidar, name='convidar'),
    path('convite/<int:convite_id>/aceitar', views.aceitar, name='aceitar'),
    path('registrar/', RegistrarUsuarioView.as_view(), name='registrar'),
    
    path('registrar/', RegistrarUsuarioView.as_view(), name='registrar'),
    path('login/', v.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', v.LogoutView.as_view(template_name='login.html'), name='logout')
    # -> O as_view() se encarrega de instanciar uma classe e registrar o usuário view 
    # direcionando para o método necessário (get, post, etc).
]

perfis/models.py
from django.db import models
from django.contrib.auth.models import User

class Perfil(models.Model):
    nome = models.CharField(max_length=255, null=False)
    telefone = models.CharField(max_length=15, null=False)
    nome_empresa = models.CharField(max_length=255, null=False)
    contatos = models.ManyToManyField('Perfil')
    usuario = models.OneToOneField(User, related_name='perfil', on_delete=models.CASCADE)
    
    @property #Toda vez que referenciar email deve apontar pra própria classe.
    def email(self): #É como se fosse o get ou set do Java.
        return self.usuario.email
    
    def ja_possui_convite(self, perfil):               
        return (Convite.objects.filter(solicitante = self, convidado = perfil).exists() or
                Convite.objects.filter(solicitante = perfil, convidado = self).exists())

    def convidar(self, perfil_convidado):
        if self.pode_convidar(perfil_convidado):
            convite = Convite(solicitante=self, convidado=perfil_convidado)
            convite.save()

    def __str__(self):
        return self.nome

    def pode_convidar(self, perfil):
        nao_pode = self.convite_a_si_mesmo(perfil) or self.ja_eh_contato(perfil) or self.ja_possui_convite(perfil)
    
    def ja_eh_contato(self, perfil):
        return self.contatos.filter(id = perfil.id).exists()

    def convite_a_si_mesmo(self, perfil):
        return self == perfil

    '''
    def __init__(self, id = 0, nome= '', email= '', telefone= '', nome_empresa= ''):
        self.id = id
        self.nome = nome
        self.email = email
        self.telefone = telefone
        self.nome_empresa = nome_empresa
    '''
        
class Convite(models.Model):
    solicitante = models.ForeignKey(Perfil, related_name = 'convites_feitos', on_delete= models.CASCADE)
    convidado = models.ForeignKey(Perfil, related_name = 'convites_recebidos', on_delete= models.CASCADE)
    
    def aceitar(self):
        self.convidado.contatos.add(self.solicitante)
        self.solicitante.contatos.add(self.convidado)
        self.delete()

# Create your models here.

usuarios/models.py
from django.db import models

# Create your models here.

usuarios/forms.py
from django import forms
from django.contrib.auth.models import User

class RegistrarUsuarioForm(forms.Form):
    nome = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    senha = forms.CharField(required=True)
    telefone = forms.CharField(required=True)
    nome_empresa = forms.CharField(required=True)

    def is_valid(self):
        valid = True
        
        if not super(RegistrarUsuarioForm, self).is_valid():
            self.adiciona_erro('Dados inválidos. Verifique os campos preenchidos.')
            valid = False
            
        user_exists = User.objects.filter(username=self.cleaned_data['nome']).exists()

        if user_exists:
            self.adiciona_erro('O usuário inserido já existe.')
            valid = False

        return valid

    def adiciona_erro(self, message):
        errors = self.errors.setdefault(forms.forms.NON_FIELD_ERRORS, forms.utils.ErrorList())
        errors.append(message)

perfis/views.py
from django.shortcuts import render
from perfis.models import Perfil
from django.shortcuts import redirect
from perfis.models import Perfil, Convite
from django.contrib.auth.decorators import login_required

@login_required
def index(request):
    return render(request, 'index.html', {'perfis' : Perfil.objects.all(),
										  'perfil_logado' : get_perfil_logado(request)})
@login_required
def exibir_perfil(request, perfil_id): 
    perfil = Perfil.objects.get(id = perfil_id)
    perfil_logado = get_perfil_logado(request)
    ja_eh_contato = perfil in perfil_logado.contatos.all()

    return render(request, 'perfil.html',
		          {'perfil' : perfil,
				  'perfil_logado' : get_perfil_logado(request),
                  'ja_eh_contado' : ja_eh_contato})

@login_required
def convidar(request, perfil_id):
    
    perfil_a_convidar = Perfil.objects.get(id = perfil_id)
    perfil_logado = get_perfil_logado(request)
    perfil_logado.convidar(perfil_a_convidar)

    return redirect('index') #Redirect apenas retorna para a página index.

@login_required
def get_perfil_logado(request):
    return request.user.perfil

@login_required
def aceitar(request, convite_id):
    convite = Convite.objects.get(id=convite_id)
    convite.aceitar()
    return redirect('index')

# Create your views here.

usuarios/views.py
from django.shortcuts import render, redirect
from django.views.generic.base import View # -> Herda de view
from django.contrib.auth.models import User
from perfis.models import Perfil
from usuarios.forms import RegistrarUsuarioForm

# Create your views here.

class RegistrarUsuarioView(View):
    template_name  = 'registrar.html'

    def get(self, request):
        return render(request, self.template_name)
    
    def post(self, request):
        form = RegistrarUsuarioForm(request.POST)

        if form.is_valid():
            dados_form = form.cleaned_data
            usuario = User.objects.create_user(dados_form['nome'],
                                               dados_form['email'],
                                               dados_form['senha'])
            
            perfil = Perfil(nome = usuario.username,
                            telefone = dados_form['telefone'],
                            nome_empresa = dados_form['nome_empresa'],
                            usuario = usuario)
            perfil.save()
            return redirect('index')

        return render(request, self.template_name, {'form' : form})

perfis/templates/base.html
{% load static %};
<!DOCTYPE html>
<html lang="pt">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width">
        <link href="{% static 'styles/bootstrap.css' %}" rel="stylesheet">
        <link href="{% static 'styles/main.css' %}" rel="stylesheet">
        <title>ConnectedIn</title>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <ul class="nav nav-pills pull-right">
                    <li class=""><a href="{% url 'index' %}">Nome</a></li>
                    <li class=""><a href="/logout/">Logout</a></li>
                </ul>
                <h3 class="text-muted">ConnectedIn</h3>
            </div>
            <div class="row content">
                {% block body %}
                {% endblock %}
            <!-- conteúdo da página entraria aqui -->
            </div>
        </div>
    </body>
</html>

perfis/templates/index.html
{% extends "base.html" %}
{% block body %}
<!DOCTYPE html>
<div class="col-lg-12">
    <div class="pane panel-default">    
        <div class="panel-heading">
            <strong>Todos os Perfis</strong>
        </div>
        {% if perfis %}
            <ul class="list-group">
                {% for perfil in perfis %}
                    <li> 
                        <a href = "{% url 'exibir' perfil.id %}"> {{ perfil.nome }} / {{ perfil.email }}</a> 
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p>Nenhum Perfil foi encontrado!</p>
        {% endif %}
    </div>  
    
    <div class="panel panel-default">
        {% with total_de_contatos=perfil_logado.contatos.count %}
            {% if total_de_contatos %}
                <div class="panel-heading">
                    <strong>Você tem {{total_de_contatos}} contato{{total_de_contatos|pluralize}}</strong>
                </div>
                <ul class="list-group">
                    {% for contato in perfil_logado.contatos.all %}
                        <a href="{% url 'exibir' contato.id %}" class="list-group-item">{{ contato.nome }} // {{ contato.email }}</a>
                    {% endfor %}
                </ul>
            {% else %}
                <div class="panel-body">
                    <p>Você não possui contatos no momento :(</p>
                </div>
            {% endif %}
        {% endwith %}
    </div>

    <div class="pane panel-default">
        {% with total_de_convites=perfil_logado.convites_recebidos.count %}
            {% if total_de_convites %}
            <div class="panel-heading">
                <strong> Você tem {{total_de_convites}} convite{{ total_de_convites|pluralize }} aguardando aprovação.
                </strong>
            </div>
            {% endif %}
        {% endwith %}
    </div>
</div>
{% endblock %}

perfis/templates/perfil.html
{% extends "base.html" %}
{% block body %}
<div class="row">
    <div class="col-lg-12">
        <h2 style="margin-top: 0">{{ perfil.nome }}</h2>
        <address>
            <strong>{{perfil.nome_empresa}}</strong><br/>
            <abbr title="Telefone">Tel: </abbr> {{perfil.telefone}}<br/>
            <a href="mailto:{{perfil.email}}">{{perfil.email}}</a>
        </address>

        {% if perfil_logado.pode_convidar %}
            <div class="well well-sm">Vocês já estão conectados!</div>
        {% else %}
            <a href= "{% url 'convidar' perfil.id %}" class="btn btn-sucess" role="button">Convidar</a>
        {% endif %}     
    </div>

    <div class="panel panel-default">
        {% if perfil_logado.convites_recebidos.count %}
            <div class="panel-heading">
                <strong>Convites aguardando aprovação</strong>
            </div>
            <ul class="list-group">
                {% for convite in perfil_logado.convites_recebidos.all %}
                    <li class="list-group-item">
                        {{ convite.solicitante.nome }}
                        <a href="{% url 'aceitar' convite.id %}" class="pull-right">Aceitar</a>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <div class="panel-body">
                <p>Nenhum convite recebido >:(</p>
            </div>
        {% endif %}
    </div>
</div>
{% endblock %}

usuarios/templates/base_usuario.html
{% load static %}
<!DOCTYPE html>
<html lang="pt">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width">
        <title>Connected In</title>
        <link href="{% static "styles/bootstrap.css" %}" rel ="stylesheet">
        <link href="{% static "styles/signin.css" %}" rel="stylesheet"> 
    </head>
    <body>
        <div class="container">
            {% block body %}
            {% endblock %}
        </div>
    </body>
</html>

usuarios/templates/login.html
{% extends "base_usuario.html" %}
{% block body %}
<form action="{% url 'login' %}" method="post">
    {% csrf_token %}
    <h2>Login</h2>
    <input id="id_username" name="username" placeholder="Nome" required autofocus>
    <input type="password" id="id_passaword" name="password" placeholder="Senha" required>
    <button type="submit" value="Login">Login</button>
    {% if form.errors %}
     <div>
         <button type="button" data-dismiss="alert" aria-hidden="true">x</button>
         Favor, verifique o email e senha informados.
     </div>
    {% endif %}
    <a href="{% url 'registrar' %}">Registre-se</a>
</form>
{% endblock %}

usuarios/templates/registrar.html
{% extends "base_usuario.html" %}
{% block body %}
    <form class="form-signin" action="{% url 'registrar' %}" method="post">
        {% csrf_token %} <!-- Serve para o django identificar que o formulário foi gerado por ele -->
        <h2 class="form-signin-heading">Crie seu usuário</h2>
        <input id="id_email" name="email" class="form-control" placeholder="Email *" required autofocus>
        <input id="id_nome" name="nome" class="form-control" placeholder="Nome *" required>
        <input type="password" id="id_senha" name="senha" class="form-control" placeholder="Senha *" required>
        <hr />
        <input id="id_telefone" name="telefone" class="form-control" placeholder="Telefone" required>
        <input id="id_nome_empresa" name="nome_empresa" class="form-control" placeholder="Empresa" required> 
        <hr />
        <button class="btn btn-lg btn-primary btn-block" type="submit" value="Login">Registrar</button>
        
        <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
            {{form.non_field_errors}}
        </div>
    </form>
{% endblock %}